FacturacionSAT.CSL.WEB/Areas/Admin/Controllers/CFDIDatosPacController.cs
using FacturacionSAT.CSL.WEB.App_Start;
using FacturacionSAT.CSL.WEB.Models.Datos;
using FacturacionSAT.CSL.WEB.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FacturacionSAT.CSL.WEB.Filters;

namespace FacturacionSAT.CSL.WEB.Areas.Admin.Controllers
{
    [Autorizado]
    public class CFDIDatosPacController : Controller
    {
        private TokenProcessor Token = TokenProcessor.GetInstance();
        string Conexion = ConfigurationManager.AppSettings.Get("strConnection");
        // GET: Admin/CFDIDatosPac
        public ActionResult Index()
        {
            try
            {
                CFDIDatosPacModels CFDIModel = new CFDIDatosPacModels();
                CFDIPacDatos CFDIDatos = new CFDIPacDatos();
                AuxSQLModel oAuxSQLModel = new AuxSQLModel();
                oAuxSQLModel.Conexion = Conexion;
                CFDIModel.ListaCFDIPac = CFDIDatos.ListaPac(oAuxSQLModel);

                return View(CFDIModel);
            }
            catch (Exception)
            {
                CFDIDatosPacModels CFDIModel = new CFDIDatosPacModels();
                TempData["typemessage"] = "2";
                TempData["message"] = "Ocurrió un error al guardar el registro.";
                return View(CFDIModel);
            }
        }
      
        [HttpGet]
        public ActionResult CreateCFDIPac()
        {
            try
            {
                Token.SaveToken();
                CFDIDatosPacModels CFDIModel = new CFDIDatosPacModels();
                CFDIPacDatos CFDIDatos = new CFDIPacDatos();
                CFDIModel.Predeterminado = true;
                return View(CFDIModel);
            }
            catch (Exception)
            {
                CFDIDatosPacModels CFDIModel = new CFDIDatosPacModels();
                TempData["typemessage"] = "2";
                TempData["message"] = "Ocurrió un error al guardar el registro.";
                return View(CFDIModel);
            }
        }

        [HttpPost]
        public ActionResult CreateCFDIPac(CFDIDatosPacModels productos)
        {
            CFDIPacDatos CFDIDatos = new CFDIPacDatos();
            try
            {
                if (Token.IsTokenValid())
                {
                    if (ModelState.IsValid)
                    {
                        productos.Conexion = Conexion;
                        productos.Id_usuario = User.Identity.Name;
                        productos.Opcion = 1;
                        productos = CFDIDatos.ABCCFDIPac(productos);

                        if (productos.Completado == true)
                        {
                            TempData["typemessage"] = "1";
                            TempData["message"] = "El registro se guardo correctamente.";
                            Token.ResetToken();
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            TempData["typemessage"] = "2";
                            TempData["message"] = "Ocurrió un error al guardar el registro.";
                            return View(productos);
                        }
                    }
                    else
                    {
                        productos.Conexion = Conexion;
                        return View(productos);
                    }
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                TempData["typemessage"] = "2";
                TempData["message"] = "No se puede cargar la vista";
                return View(productos);
            }
        }

        [HttpGet]
        public ActionResult UpdateCFDIPac(string id)
        {
            try
            {
                Token.SaveToken();
                CFDIDatosPacModels CFDIModel = new CFDIDatosPacModels();
                CFDIPacDatos CFDIDatos = new CFDIPacDatos();
                CFDIModel.Id_cfdiDatosPac = id;
                CFDIModel.Conexion = Conexion;
                CFDIModel = CFDIDatos.GetCFDIPacDetail(CFDIModel);
                return View(CFDIModel);
            }
            catch (Exception)
            {
                CFDIDatosPacModels CFDIModel = new CFDIDatosPacModels();
                TempData["typemessage"] = "2";
                TempData["message"] = "No se puede cargar la vista";
                return View(CFDIModel);
            }
        }
        [HttpPost]
        public ActionResult UpdateCFDIPac(string id, CFDIDatosPacModels productos)
        {
            
                CFDIPacDatos CFDIDatos = new CFDIPacDatos();
                try
                {
                    if (Token.IsTokenValid())
                    {
                        if (ModelState.IsValid)
                        {
                            productos.Conexion = Conexion;
                            productos.Id_usuario = User.Identity.Name;
                            productos.Opcion = 2;
                            productos.Id_cfdiDatosPac = id;
                            productos = CFDIDatos.ABCCFDIPac(productos);

                            if (productos.Completado == true)
                            {
                                TempData["typemessage"] = "1";
                                TempData["message"] = "El registro se guardo correctamente.";
                                Token.ResetToken();
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                TempData["typemessage"] = "2";
                                TempData["message"] = "Ocurrió un error al guardar el registro.";
                                return View(productos);
                            }
                        }
                        else
                        {                            
                            return View(productos);
                        }
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception)
                {
                    TempData["message"] = "Ocurrió un error al guardar el registro.";
                    return View(productos);
                }        
        }

        [HttpGet]
        public ActionResult DeleteCFDIPac(string id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult DeleteCFDIPac(string id, FormCollection collection)
        {
            try
            {
                CFDIDatosPacModels CFDIModel = new CFDIDatosPacModels();
                CFDIPacDatos CFDIDatos = new CFDIPacDatos();
                //AuxSQLModel oAuxSQLModel = new AuxSQLModel();
                CFDIModel.Conexion = Conexion;
                CFDIModel.Opcion = 3;
                CFDIModel.Id_cfdiDatosPac = id;
                //CFDIModel.Predeterminado = id2;
                CFDIModel.Id_usuario = User.Identity.Name;
                CFDIModel = CFDIDatos.ABCCFDIPac(CFDIModel);

                if (CFDIModel.Id_cfdiDatosPac == "")
                {
                    return RedirectToAction("Index");
                }

                return Json("");               
            }
            catch
            {
                CFDIDatosPacModels CFDIModel = new CFDIDatosPacModels();
                TempData["typemessage"] = "2";
                TempData["message"] = "Ocurrió un error al guardar el registro.";
                return View(CFDIModel);
            }
        }
    }
}

FacturacionSAT.CSL.WEB/Areas/Admin/Views/CFDIDatosPac/CreateCFDIPac.cshtml
@model FacturacionSAT.CSL.WEB.Models.CFDIDatosPacModels
@{
    ViewBag.Title = "CreateCFDIPac";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section featured{

    @{
        var message = TempData["message"] ?? string.Empty;
        var typemessage = TempData["typemessage"] ?? string.Empty;
    }
    <div class="row">
        <div id="Error" class="progress-bar progress-bar-striped active errorCSL" style="display:none; width:100%">
            <h3></h3>
        </div>
        <div id="Success" class="progress-bar progress-bar-striped active successCSL" style="display:none; width:100%">
            <h3></h3>
        </div>
        <div class="col-md-12">           
            @{ Html.EnableClientValidation(false); }
            @using (Html.BeginForm("CreateCFDIPac", "CFDIDatosPac", FormMethod.Post, new { id = "form-DatosPac", @class = "form-horizontal", autocomplete = "off" }))
            {

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(false, "Hay errores en la captura de información:", new { @class = "text-danger" }) //Server
                <div id="validation_summary" class="field_error "></div> //JS

                @Html.HiddenFor(model => model.Id_cfdiDatosPac)
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Crear</strong> CFDIPac</h3>
                        <ul class="panel-controls">
                            <li><a href="#" class="panel-remove exsa"><span class="fa fa-times"></span></a></li>
                        </ul>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-12 col-xs-12 control-label text-center">Descripción</label>
                                    <div class="col-md-12 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon"><span class="fa fa-pencil"></span></span>                                        
                                            @Html.TextBoxFor(model => model.Descripcion, new { id = "Descripcion", @class = "form-control" })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.Descripcion)
                                        <span class="help-block">Ingrese una Descripcion</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-12 control-label text-center">User Pac</label>
                                    <div class="col-md-12 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon"><span class="fa fa-pencil"></span></span>                                
                                            @Html.TextBoxFor(model => model.UserPac, new { id = "UserPac", @class = "form-control" })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.UserPac)
                                        <span class="help-block">Clave Usuario Pac</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-12 control-label text-center">Password Pac</label>
                                    <div class="col-md-12 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon"><span class="fa fa-unlock-alt"></span></span>                        
                                            @Html.PasswordFor(model => model.PasswordPac, new { id = "PasswordPac", @class = "form-control" })
                                            <div class="input-group-addon">
                                                <span id="show_password" class="fa fa-eye-slash icon" />
                                            </div>
                                        </div>
                                        @Html.ValidationMessageFor(model => model.PasswordPac)
                                        <span class="help-block">Ingrese Contraseña Pac</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-12 control-label text-center">User Pac Test</label>
                                    <div class="col-md-12 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon"><span class="fa fa-pencil"></span></span>                                           
                                            @Html.TextBoxFor(model => model.UserPacTest, new { id = "UserPacTest", @class = "form-control" })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.UserPacTest)
                                        <span class="help-block">Ingrese Usuario Pac Test</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-12 control-label text-center">Password Pac Test</label>
                                    <div class="col-md-12 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon"><span class="fa fa-unlock-alt"></span></span>                                           
                                            @Html.PasswordFor(model => model.PasswordPacTest, new { id = "PasswordPacTest", @class = "form-control" })
                                            <div class="input-group-addon">
                                                <span id="show_password1" class="fa fa-eye-slash icon1" />
                                            </div>
                                        </div>
                                        @Html.ValidationMessageFor(model => model.PasswordPacTest)
                                        <span class="help-block">Ingrese contraseña Pact Test</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-6 control-label">¿Es Predeterminado?</label>
                                    <div class="text-center col-md-9">
                                        @Html.CheckBoxFor(model => model.Predeterminado)
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <input type="submit" value="Guardar" class="btn btn-primary pull-right">
                        <a href="@Url.Action("Index","CFDIDatosPac")" class="btn btn-danger"><i class="icon-prev"></i>Cancelar</a>
                    </div>
                </div>             
             }
        </div>
    </div>
    <script>
        var message = '@message';
        var typemessage = '@typemessage';
    </script>
}
@section script{
    <script type="text/javascript" src="@Url.Content("~/Content/js/mensajeDeError.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/plugins/jquery-validation/jquery.validate.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/validaciones/additionals.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/DatosPac.js")"></script>
    <script>
        jQuery(document).ready(function () {

            Mensaje(message, typemessage);
            DatosPac.init();
        });
    </script>
}

FacturacionSAT.CSL.WEB/Areas/Admin/Views/CFDIDatosPac/Index.cshtml
@model FacturacionSAT.CSL.WEB.Models.CFDIDatosPacModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section featured{
    @{
        var message = TempData["message"] ?? string.Empty;
        var typemessage = TempData["typemessage"] ?? string.Empty;
    }
    <div id="Error" class="progress-bar progress-bar-striped active errorCSL" style="display:none; width:100%">
        <h3></h3>
    </div>
    <div id="Success" class="progress-bar progress-bar-striped active successCSL" style="display:none; width:100%">
        <h3></h3>
    </div>
    <div class="page-title">
        <h2><span class="fa fa-arrow-circle-o-left"></span><strong>CFDIPAC</strong> </h2>
    </div>
    <!-- END PAGE TITLE -->
    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">
        <div class="row">
            <div class="col-md-12">
                <!-- START DEFAULT DATATABLE -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                        <ul class="panel-controls">
                            <li><a href="@Url.Action("CreateCFDIPac","CFDIDatosPac")" class="btn btn-default btnCrear"><span class="fa fa-plus"></span> Nuevo</a></li>
                            <li><a href="#" class="panel-collapse exsa"><span class="fa fa-angle-down"></span></a></li>
                            <li><a href="#" class="panel-fullscreen exsa"><span class="fa fa-expand"></span></a></li>
                        </ul>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>Descripción</th>
                                        <th>UserPac</th>
                                        <th>UserPacTest</th>
                                        <th>Predeterminado</th>
                                        @*<th>PasswordPac</th>
                                            <th>PasswordPacTest</th>*@
                                        <th>Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.ListaCFDIPac)
                                    {
                                        <tr id="@item.Id_cfdiDatosPac">
                                            <td>@item.Descripcion</td>
                                            <td>@item.UserPac</td>
                                            <td>@item.UserPacTest</td>
                                            <td>
                                                @if (item.Predeterminado == true)
                                                {
                                                    <span class="badge badge-warning">SI</span>
                                                }
                                                else
                                                {
                                                    <span class="badge badge-danger">NO</span>
                                                }
                                            </td>
                                            @*<td>@item.PasswordPac</td>
                                                <td>@item.PasswordPacTest</td>*@
                                            <td style="text-align:center;">
                                                <div class="visible-md visible-lg hidden-sm hidden-xs">
                                                    <a title="Editar" href="@Url.Action("UpdateCFDIPac","CFDIDatosPac",new { id = item.Id_cfdiDatosPac })" class="btn btn-yellow tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
                                                    <a title="Eliminar" id="delete-@item.Id_cfdiDatosPac" data-hrefa="@Url.Action("DeleteCFDIPac", "CFDIDatosPac", new { id = item.Id_cfdiDatosPac })" onClick="delete_row('@item.Id_cfdiDatosPac');" class="btn btn-danger tooltips" data-placement="top" data-original-title="Eliminar"><i class="fa fa-trash-o"></i></a>
                                                </div>
                                                <div class="visible-xs visible-sm hidden-md hidden-lg">
                                                    <div class="btn-group">
                                                        <a class="btn btn-danger dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
                                                            <i class="fa fa-cog"></i> <span class="caret"></span>
                                                        </a>
                                                        <ul role="menu" class="dropdown-menu pull-right dropdown-dark">
                                                            <li>
                                                                <a role="menuitem" tabindex="-1" href="@Url.Action("UpdateCFDIPac", "CFDIDatosPac", new { id = item.Id_cfdiDatosPac})">
                                                                    <i class="fa fa-edit"></i> Editar
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a role="menuitem" tabindex="-1" id="delete-@item.Id_cfdiDatosPac" data-hrefa="@Url.Action("DeleteCFDIPac", "CFDIDatosPac", new { id = item.Id_cfdiDatosPac})" onClick="delete_row('@item.Id_cfdiDatosPac');">
                                                                    <i class="fa fa-trash-o"></i> Eliminar
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END DEFAULT DATATABLE -->
            </div>
        </div>
    </div>
    <!-- PAGE CONTENT WRAPPER -->
    <div class="message-box animated fadeIn" data-sound="alert" id="mb-remove-row">
        <div class="mb-container">
            <div class="mb-middle">
                <div class="mb-title"><span class="fa fa-times"></span> Eliminar <strong>Registro</strong> ?</div>
                <div class="mb-content">
                    <p>¿Seguro que quieres eliminar esta fila?</p>
                    <p>Presione "sí" si está seguro.</p>
                </div>
                <div class="mb-footer">
                    <div class="pull-right">
                        <button class="btn btn-success btn-lg mb-control-yes">Si</button>
                        <button class="btn btn-default btn-lg mb-control-close">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    var message = '@message';
    var typemessage = '@typemessage';
    </script>
}
@section script
{
    @*<script type="text/javascript" src="@Url.Content("~/Content/js/demo_tables.js")"></script>*@
    <script type="text/javascript" src="@Url.Content("~/Content/js/demo_DatosPac.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/mensajeDeError.js")"></script>
    <script>
        jQuery(document).ready(function () {
            Mensaje(message, typemessage);
        });
    </script>
}