FacturacionSAT.CSL.WEB/Models/CFDIDatosEmisor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FacturacionSAT.CSL.WEB.Models
{
    public class CFDIDatosEmisor
    {
        public CFDIDatosEmisor()
        {
            _IDCFDIDatosEmisor = string.Empty;
            _IDCFDIRegimenFiscalDetalle = string.Empty;
            _IDCFDITipoPersona = string.Empty;
            _RazonSocial = string.Empty;
            _RFC = string.Empty;
            _Direccion = string.Empty;
            _CodigoPostal = string.Empty;
            _Correo = string.Empty;
            _Password = string.Empty;
            _URLArchivoCER = string.Empty;
            _URLArchivoKEY = string.Empty;
            _Imagen = string.Empty;
            _PasswordArchivoKEY = string.Empty;
            _CFDITipoPersona = new CFDITipoPersonaModels();
        }

        private string _IDCFDIDatosEmisor;

        public string IDCFDIDatosEmisor
        {
            get { return _IDCFDIDatosEmisor; }
            set { _IDCFDIDatosEmisor = value; }
        }

        private string _IDCFDITipoPersona;

        public string IDCFDITipoPersona
        {
            get { return _IDCFDITipoPersona; }
            set { _IDCFDITipoPersona = value; }
        }

        private string _RazonSocial;

        public string RazonSocial
        {
            get { return _RazonSocial; }
            set { _RazonSocial = value; }
        }

        private string _RFC;

        public string RFC
        {
            get { return _RFC; }
            set { _RFC = value; }
        }

        private string _IDCFDIRegimenFiscalDetalle;

        public string IDCFDIReqgimenFiscalDetalle
        {
            get { return _IDCFDIRegimenFiscalDetalle; }
            set { _IDCFDIRegimenFiscalDetalle = value; }
        }

        private string _Direccion;

        public string Direccion
        {
            get { return _Direccion; }
            set { _Direccion = value; }
        }

        private string _CodigoPostal;

        public string CodigoPostal
        {
            get { return _CodigoPostal; }
            set { _CodigoPostal = value; }
        }

        private bool _Predeterminado;

        public bool Predeterminado
        {
            get { return _Predeterminado; }
            set { _Predeterminado = value; }
        }

        private string _Correo;

        public string Correo
        {
            get { return _Correo; }
            set { _Correo = value; }
        }

        private string _Password;

        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        private string _URLArchivoCER;

        public string URLArchivoCER
        {
            get { return _URLArchivoCER; }
            set { _URLArchivoCER = value; }
        }

        private string _URLArchivoKEY;

        public string URLArchivoKEY
        {
            get { return _URLArchivoKEY; }
            set { _URLArchivoKEY = value; }
        }

        private string _PasswordArchivoKEY;

        public string PasswordArchivoKEY
        {
            get { return _PasswordArchivoKEY; }
            set { _PasswordArchivoKEY = value; }
        }

        private string _Imagen;

        public string Imagen
        {
            get { return _Imagen; }
            set { _Imagen = value; }
        }

        private CFDITipoPersonaModels _CFDITipoPersona;

        public CFDITipoPersonaModels CFDITipoPersona
        {
            get { return _CFDITipoPersona; }
            set { _CFDITipoPersona = value; }
        }


        public string Conexion { get; set; }
        public int Resultado { get; set; }
        public int Opcion { get; set; }
        public string IDUsuario { get; set; }
    }
}

FacturacionSAT.CSL.WEB/Areas/Admin/Controllers/CFDIDatosEmisorController.cs
using FacturacionSAT.CSL.WEB.App_Start;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FacturacionSAT.CSL.WEB.Models;
using FacturacionSAT.CSL.WEB.Models.Datos;
using System.IO;
using System.Drawing;
using FacturacionSAT.CSL.WEB.Filters;

namespace FacturacionSAT.CSL.WEB.Areas.Admin.Controllers
{
    [Autorizado]
    public class CFDIDatosEmisorController : Controller
    {
        private TokenProcessor Token = TokenProcessor.GetInstance();
        string Conexion = ConfigurationManager.AppSettings.Get("strConnection");
        // GET: Admin/CFDIDatosEmisor
        public ActionResult Index()
        {
            try
            {
                CFDIDatosEmisorModels DatosEmisor = new CFDIDatosEmisorModels();
                CFDIDatosEmisorDatos Datos = new CFDIDatosEmisorDatos();
                DatosEmisor.Conexion = Conexion;
                DatosEmisor.ListaDatosEmisor = Datos.IndexCFDIDatosEmisor(DatosEmisor);
                return View(DatosEmisor);
            }
            catch (Exception ex)
            {
                CFDIDatosEmisorModels DatosEmisor = new CFDIDatosEmisorModels();
                TempData["typemessage"] = "2";
                TempData["message"] = "No se puede cargar la vista";
                return View(DatosEmisor);
            }
        }
        // GET: Admin/CFDIDatosEmisor/Create
        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                Token.SaveToken();
                CFDIDatosEmisorModels DatosEmisor = new CFDIDatosEmisorModels();
                CFDIDatosEmisorDatos Datos = new CFDIDatosEmisorDatos();
                DatosEmisor.Conexion = Conexion;
                DatosEmisor.ListaTipoPersona = Datos.ListaPersonaCMB(DatosEmisor);
                return View(DatosEmisor);
            }
            catch (Exception)
            {

                throw;
            }
        }
        // POST: Admin/CFDIDatosEmisor/Create(Model)
        [HttpPost]
        public ActionResult Create(CFDIDatosEmisorModels DatosAux, HttpPostedFileBase file)
        {
            try
            {
                CFDIDatosEmisorDatos Datos = new CFDIDatosEmisorDatos();
                if (Token.IsTokenValid())
                {
                    if (ModelState.IsValid)
                    {
                        DatosAux.Conexion = Conexion;
                        DatosAux.Opcion = 1;
                        DatosAux.IDUsuario = User.Identity.Name;
                        DatosAux = Datos.AbcDatosEmisor(DatosAux);
                        if (!string.IsNullOrEmpty(DatosAux.IDCFDIDatosEmisor))
                        {
                            HttpPostedFileBase bannerImage = Request.Files[0] as HttpPostedFileBase;
                            if (!string.IsNullOrEmpty(bannerImage.FileName))
                            {
                                if (bannerImage != null && bannerImage.ContentLength > 0)
                                {
                                    string baseDir = Server.MapPath("~/SAT/SAT1/");
                                    string fileExtension = Path.GetExtension(bannerImage.FileName);
                                    string fileName = DatosAux.IDCFDIDatosEmisor + fileExtension;
                                    bannerImage.SaveAs(baseDir + fileName);
                                    DatosAux.URLArchivoCER = "~/SAT/SAT1/" + fileName;
                                }
                            }
                            HttpPostedFileBase bannerImage1 = Request.Files[1] as HttpPostedFileBase;
                            if (!string.IsNullOrEmpty(bannerImage1.FileName))
                            {
                                if (bannerImage1 != null && bannerImage1.ContentLength > 0)
                                {
                                    string baseDir = Server.MapPath("~/SAT/SAT1/");
                                    string fileExtension = Path.GetExtension(bannerImage1.FileName);
                                    string fileName = DatosAux.IDCFDIDatosEmisor + fileExtension;
                                    bannerImage1.SaveAs(baseDir + fileName);
                                    DatosAux.URLArchivoKEY = "~/SAT/SAT1/" + fileName;
                                }
                            }
                            HttpPostedFileBase bannerImage2 = Request.Files[2] as HttpPostedFileBase;
                            if (!string.IsNullOrEmpty(bannerImage2.FileName))
                            {
                                if (bannerImage2 != null && bannerImage2.ContentLength > 0)
                                {
                                    string baseDir = Server.MapPath("~/SAT/SAT1/");
                                    string fileExtension = Path.GetExtension(bannerImage2.FileName);
                                    string fileName = DatosAux.IDCFDIDatosEmisor + fileExtension;
                                    bannerImage2.SaveAs(baseDir + fileName);
                                    DatosAux.Imagen = "~/SAT/SAT1/" + fileName;
                                }
                            }
                            DatosAux.Opcion = 4;
                            DatosAux = Datos.AbcDatosEmisor(DatosAux);
                            if (!string.IsNullOrEmpty(DatosAux.IDCFDIDatosEmisor))
                            {
                                TempData["typemessage"] = "1";
                                TempData["message"] = "Los datos se guardarón correctamente.";
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                DatosAux.ListaTipoPersona = Datos.ListaPersonaCMB(DatosAux);
                                TempData["typemessage"] = "2";
                                TempData["message"] = "Ocurrio un error al intentar guardar las los archivo con las extenciones. CER, KEY, IMG";
                                return View(DatosAux);
                            }
                        }
                        else
                        {
                            DatosAux.ListaTipoPersona = Datos.ListaPersonaCMB(DatosAux);
                            TempData["typemessage"] = "2";
                            TempData["message"] = "Ocurrio un error al intentar guardar los datos.";
                            return View(DatosAux);
                        }
                    }
                    else
                    {
                        DatosAux.Conexion = Conexion;
                        DatosAux.ListaTipoPersona = Datos.ListaPersonaCMB(DatosAux);
                        return View(Datos);
                    }
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["typemessage"] = "2";
                TempData["message"] = "Ocurrio un error.Por favor contacte a soporte técnico";
                return RedirectToAction("Index");
            }
        }

        //GET:Admi/CFDIDatosEmisor/Create/id
        [HttpGet]
        public ActionResult Edit(string id)
        {
            try
            {
                Token.SaveToken();
                CFDIDatosEmisorModels DatosEmisor = new CFDIDatosEmisorModels();
                CFDIDatosEmisorDatos Datos = new CFDIDatosEmisorDatos();
                DatosEmisor.Conexion = Conexion;
                DatosEmisor.IDCFDIDatosEmisor = id;
                DatosEmisor.ListaTipoPersona = Datos.ListaPersonaCMB(DatosEmisor);
                DatosEmisor = Datos.ObtenerDatosEmisorID(DatosEmisor);
                DatosEmisor.ListaRegimenFiscalDetalle = Datos.ListaRegimenFiscalDetalle(DatosEmisor);
                return View(DatosEmisor);
            }
            catch (Exception)
            { 
                throw;
            }
        }

        //POST:Admi/CFDIDatosEmisor/Create/id
        [HttpPost]
        public ActionResult Edit(CFDIDatosEmisorModels DatosAux)
        {
            try
            {
                CFDIDatosEmisorDatos Datos = new CFDIDatosEmisorDatos();
                if (Token.IsTokenValid())
                {
                    if (ModelState.IsValid)
                    {
                        DatosAux.Conexion = Conexion;
                        DatosAux.Opcion = 2;
                        DatosAux.IDUsuario = User.Identity.Name;
                        DatosAux = Datos.AbcDatosEmisor(DatosAux);
                        if (!string.IsNullOrEmpty(DatosAux.IDCFDIDatosEmisor))
                        {
                            HttpPostedFileBase bannerImage = Request.Files[0] as HttpPostedFileBase;
                            if (!string.IsNullOrEmpty(bannerImage.FileName))
                            {
                                if (bannerImage != null && bannerImage.ContentLength > 0)
                                {
                                    string baseDir = Server.MapPath("~/SAT/SAT1/");
                                    string fileExtension = Path.GetExtension(bannerImage.FileName);
                                    string fileName = DatosAux.IDCFDIDatosEmisor + fileExtension;
                                    bannerImage.SaveAs(baseDir + fileName);
                                    DatosAux.URLArchivoCER = "~/SAT/SAT1/" + fileName;
                                }
                            }
                            HttpPostedFileBase bannerImage1 = Request.Files[1] as HttpPostedFileBase;
                            if (!string.IsNullOrEmpty(bannerImage1.FileName))
                            {
                                if (bannerImage1 != null && bannerImage1.ContentLength > 0)

FacturacionSAT.CSL.WEB/Areas/Admin/Views/CFDIDatosEmisor/Index.cshtml
@model FacturacionSAT.CSL.WEB.Models.CFDIDatosEmisorModels

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section featured{
    @{
        var message = TempData["message"] ?? string.Empty;
        var typemessage = TempData["typemessage"] ?? string.Empty;
    }
    <div id="Error" class="progress-bar progress-bar-striped active errorCSL" style="display:none; width:100%">
        <h3></h3>
    </div>
    <div id="Success" class="progress-bar progress-bar-striped active successCSL" style="display:none; width:100%">
        <h3></h3>
    </div>
    <div class="page-title">
        <h2><span class="fa fa-arrow-circle-o-left"></span> CFDI DATOS EMISOR </h2>
    </div>
    <!-- END PAGE TITLE -->
    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">
        <div class="row">
            <div class="col-md-12">
                <!-- START DEFAULT DATATABLE -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                        <ul class="panel-controls">
                            <li><a href="@Url.Action("Create","CFDIDatosEmisor")" class="btn btn-default btnCrear"><span class="fa fa-plus"></span> Nuevo Emisor</a></li>
                            <li><a href="#" class="panel-collapse exsa"><span class="fa fa-angle-down"></span></a></li>
                            <li><a href="#" class="panel-fullscreen exsa"><span class="fa fa-expand"></span></a></li>
                        </ul>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>Tipo Persona</th>
                                        <th>Razón Social</th>
                                        <th>RFC</th>
                                        @*<th>Regimen Fiscal</th>*@
                                        <th>Regimen Fiscal</th>
                                        <th>Dirección</th>
                                        <th>C.P.</th>
                                        <th>Predeterminado</th>
                                        <th>Correo</th>
                                        <th>Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var CFDIEmisor in Model.ListaDatosEmisor)
                                    {
                                        <tr id="@CFDIEmisor.IDCFDIDatosEmisor">
                                            <td>@CFDIEmisor.CFDITipoPersona.TipoPersona</td>
                                            <td>@CFDIEmisor.RazonSocial</td>
                                            <td>@CFDIEmisor.RFC</td>
                                            @*<td>@CFDIEmisor.CFDIRegimenFiscalDetalle.C_RegimenFiscal</td>*@
                                            <td>@CFDIEmisor.CFDIRegimenFiscalDetalle.Descripcion</td>
                                            <td>@CFDIEmisor.Direccion</td>
                                            <td>@CFDIEmisor.CodigoPostal</td>
                                            <td>
                                                @if (CFDIEmisor.Predeterminado == true)
                                                {
                                                    <span class="badge badge-warning">SI</span>
                                                }
                                                else
                                                {
                                                    <span class="badge badge-danger">NO</span>
                                                }
                                            </td>
                                            <td>@CFDIEmisor.Correo</td>
                                            <td style="text-align:center;">
                                                <div class="visible-md visible-lg hidden-sm hidden-xs">
                                                    <a title="Editar" href="@Url.Action("Edit", "CFDIDatosEmisor", new { id = CFDIEmisor.IDCFDIDatosEmisor})" class="btn btn-yellow tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
                                                    <a title="Eliminar" id="delete-@CFDIEmisor.IDCFDIDatosEmisor" data-hrefa="@Url.Action("Delete", "CFDIDatosEmisor", new { id =  CFDIEmisor.IDCFDIDatosEmisor })" onClick="delete_row('@CFDIEmisor.IDCFDIDatosEmisor');" class="btn btn-danger tooltips" data-placement="top" data-original-title="Eliminar"><i class="fa fa-trash-o"></i></a>
                                                </div>
                                                <div class="visible-xs visible-sm hidden-md hidden-lg">
                                                    <div class="btn-group">
                                                        <a class="btn btn-danger dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
                                                            <i class="fa fa-cog"></i> <span class="caret"></span>
                                                        </a>
                                                        <ul role="menu" class="dropdown-menu pull-right dropdown-dark">
                                                            <li>
                                                                <a role="menuitem" tabindex="-1" href="@Url.Action("Edit", "CFDIDatosEmisor", new { id = CFDIEmisor.IDCFDIDatosEmisor})">
                                                                    <i class="fa fa-edit"></i> Editar
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a role="menuitem" tabindex="-1" id="delete-@CFDIEmisor.IDCFDIDatosEmisor" data-hrefa="@Url.Action("Delete", "CFDIDatosEmisor", new { id = CFDIEmisor.IDCFDIDatosEmisor })" onClick="delete_row('@CFDIEmisor.IDCFDIDatosEmisor');">
                                                                    <i class="fa fa-trash-o"></i> Eliminar
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END DEFAULT DATATABLE -->
            </div>
        </div>
    </div>
    <!-- PAGE CONTENT WRAPPER -->
    <div class="message-box animated fadeIn" data-sound="alert" id="mb-remove-row">
        <div class="mb-container">
            <div class="mb-middle">
                <div class="mb-title"><span class="fa fa-times"></span> Eliminar <strong>Registro</strong> ?</div>
                <div class="mb-content">
                    <p>¿Seguro que quieres eliminar esta fila?</p>
                    <p>Presione "sí" si está seguro.</p>
                </div>
                <div class="mb-footer">
                    <div class="pull-right">
                        <button class="btn btn-success btn-lg mb-control-yes">Si</button>
                        <button class="btn btn-default btn-lg mb-control-close">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    var message = '@message';
    var typemessage = '@typemessage';
    </script>
}
@section script
{
    @*<script type="text/javascript" src="@Url.Content("~/Content/js/demo_tables.js")"></script>*@
    <script type="text/javascript" src="@Url.Content("~/Content/js/demo_DatosEmisor.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/mensajeDeError.js")"></script>
    <script>
        jQuery(document).ready(function () {
            Mensaje(message, typemessage);
        });
    </script>
}