FacturacionSAT.CSL.WEB/Areas/Admin/Controllers/AdminFacturaController.cs
using FacturacionSAT.CSL.WEB.Filters;
using FacturacionSAT.CSL.WEB.Models;
using FacturacionSAT.CSL.WEB.Models.Datos;
using FacturacionSAT.CSL.WEB.Models.ViewModel;
using FacturacionSAT.CSL.WEB.SystemHelper;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Serialization;

namespace FacturacionSAT.CSL.WEB.Areas.Admin.Controllers
{
    [Autorizado]
    public class AdminFacturaController : Controller
    {
        private string Conexion = ConfigurationManager.AppSettings.Get("strConnection");
        private string pathXML, idFile, pathRootSystemHelperSAT, pahtRootSATTempFile, pathHTMLTempFilePDF, pathRootSATEmisorXML;
        
        //tabla index
        [HttpPost]
        public ActionResult DtFactura(DataTableParameters dataTableParameters)
        {

            AuxSQLModel oAuxSQLModel = new AuxSQLModel();
            oAuxSQLModel.Conexion = Conexion;

            JsonDatos oJsonDatos = new JsonDatos();
            oJsonDatos.DtFactura_get_Facturas(oAuxSQLModel, dataTableParameters);

            return Content(oAuxSQLModel.Mensaje);
        }

        //reimpresion
        [HttpGet]
        public ActionResult Reimpresion(int? id, string codigoBarra)
        {
            try
            {
                if((id == null || id <= 0) || (string.IsNullOrEmpty(codigoBarra) || codigoBarra.Length != 14))
                {
                    return RedirectToAction("Index");
                }

                AuxSQLModel oAuxSQLModel = new AuxSQLModel();
                FacturaDatos oFacturaDatos = new FacturaDatos();

                oAuxSQLModel.Conexion = Conexion;

                FacturaReimpresionModel oReimpresionModel = oFacturaDatos.Factura_get_AdminReimpresion(oAuxSQLModel, id.Value, codigoBarra);
                if (oAuxSQLModel.Success)
                {
                    //guardamos el string en un archivo
                    idFile = Guid.NewGuid().ToString();
                    string getNameXML = idFile + ".xml";
                    pahtRootSATTempFile = Server.MapPath("~/SATTempFile");
                    pathXML = pahtRootSATTempFile + "\\" + getNameXML;

                    System.IO.File.WriteAllText(pathXML, oReimpresionModel.XMLFactura);

                    //generamos un objeto comprobante ya que la mayoría de la informacion de la factura esta en el xml
                    Comprobante oComprobante = GenerarComprobanteDeXMLPath();

                    if (System.IO.File.Exists(pathXML))
                    {
                        System.IO.File.Delete(pathXML);
                    }
                    FacturacionViewModel oFactura = new FacturacionViewModel();

                    oFactura.Id_factura = oReimpresionModel.Id;
                    oFactura.Version = oComprobante.Version;
                    oFactura.TipoComprobante = oComprobante.TipoDeComprobante;
                    oFactura.Moneda = oComprobante.Moneda;
                    oFactura.Subtotal = oComprobante.SubTotal;
                    oFactura.TotalDescuento = oComprobante.Descuento;
                    oFactura.Total = oComprobante.Total;
                    oFactura.LugarExpedicion = oComprobante.LugarExpedicion;
                    oFactura.CodigoBarraBoleto = oReimpresionModel.CodigoBarra; 
                    oFactura.FormaDePago = oComprobante.FormaPago;
                    oFactura.RegimenFiscal = oComprobante.Emisor.RegimenFiscal;
                    oFactura.Folio = oComprobante.Folio;
                    oFactura.Fecha = DateTime.Now;

                    oFactura.RFCReceptor = oComprobante.Receptor.Rfc;
                    oFactura.RazonSocial = oComprobante.Receptor.Nombre;
                    oFactura.UsoCFDI = oComprobante.Receptor.UsoCFDI;

                    oAuxSQLModel.ResetValuesSQL();

                    oFacturaDatos.Factura_get_Generales_AdminReimpresion(oAuxSQLModel, oReimpresionModel.CodigoBarra, oComprobante, oFactura);

                    if (oAuxSQLModel.Success)
                    {
                        for (int i = 0; i < oComprobante.Conceptos.Length; i++)
                        {
                            oFactura.Conceptos[i].Descripcion = oComprobante.Conceptos[i].Descripcion;
                            oFactura.Conceptos[i].PrecioUnitario = oComprobante.Conceptos[i].ValorUnitario;
                            oFactura.Conceptos[i].Impuestos[0].TasaOCuota = oComprobante.Conceptos[i].Impuestos.Traslados[0].TasaOCuota;
                            oFactura.Conceptos[i].Impuestos[0].Importe = oComprobante.Conceptos[i].Impuestos.Traslados[0].Importe;
                            oFactura.Conceptos[i].Impuestos[0].Clave_Impuesto = oComprobante.Conceptos[i].Impuestos.Traslados[0].Impuesto;
                            oFactura.Conceptos[i].Impuestos[0].TipoFactor = oComprobante.Conceptos[i].Impuestos.Traslados[0].TipoFactor;
                            oFactura.Conceptos[i].Descuento = oComprobante.Conceptos[i].Descuento;
                        }
                        return View(oFactura);
                    }
                    else
                    {
                        TempData["message"] = "Hubo un error al obtener los datos, contacte con soporte técnico.";
                        TempData["typemessage"] = "2";

                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    TempData["message"] = "Verifique sus datos";
                    TempData["typemessage"] = "2";

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                if (System.IO.File.Exists(pathXML))
                {
                    System.IO.File.Delete(pathXML);
                }
                string Mensaje = ex.Message.Replace("\r\n", "").Replace("\r", "").Replace("\n", "");
                TempData["message"] = "Hubo un error al obtener los datos, contacte con soporte técnico.";
                TempData["typemessage"] = "2";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PreventDuplicateRequest]
        public ActionResult Reimpresion(FacturacionViewModel Factura)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AuxSQLModel oAuxSQLModel = new AuxSQLModel();
                    FacturaDatos oFacturaDatos = new FacturaDatos();

                    oAuxSQLModel.Conexion = Conexion;

                    FacturaReimpresionModel oReimpresionModel = oFacturaDatos.Factura_get_AdminReimpresion(oAuxSQLModel, Factura.Id_factura, Factura.CodigoBarraBoleto);

                    if (oAuxSQLModel.Success)
                    {
                        //guardamos el string en un archivo
                        /**************************************/
                        /*paths*/
                        idFile = Guid.NewGuid().ToString();
                        string getNameXML = idFile + ".xml";
                        pahtRootSATTempFile = Server.MapPath("~/SATTempFile");
                        pathXML = pahtRootSATTempFile + "\\" + getNameXML;
                        pathRootSystemHelperSAT = Server.MapPath("~/SystemHelper/SAT");
                        /**************************************/
                        //generamos el xml
                        System.IO.File.WriteAllText(pathXML, oReimpresionModel.XMLFactura);
                        //generamos un objeto comprobante ya que la mayoría de la informacion de la factura esta en el xml
                        Comprobante oComprobante = GenerarComprobanteDeXMLPath();

                        oAuxSQLModel.ResetValuesSQL();
                        CFDIDatosEmisorModels oEmisor = new CFDIDatosEmisorModels();
                        CFDIDatosEmisorDatos oEmisorDatos = new CFDIDatosEmisorDatos();
                        oEmisor = oEmisorDatos.ObtenerDatosEmisorPredeterminado(oAuxSQLModel);
                        Factura.Logotipo = Server.MapPath(oEmisor.Imagen);

                        if (GenerarPDFReimpresion(oComprobante, Factura))
                        {
                            TempData["message"] = "Archivo pdf creado con éxito.";
                            /*Obtenemos los datos del emisor*/

                            oAuxSQLModel.ResetValuesSQL();
                            oAuxSQLModel.Conexion = Conexion;
                            Factura.EmailEmisor = oEmisor.Correo;
                            oFacturaDatos.Factura_Save_Factura_ReimpresionFactura(oAuxSQLModel, Factura); //guardamos la factura, ya generada

                            List<string> ListaPathArchivos = new List<string>();

                            ListaPathArchivos.Add(pathXML);
                            ListaPathArchivos.Add(pathHTMLTempFilePDF);

                            if (EnviarFacturaEmail(oEmisor.Correo, oEmisor.Password, Factura.EmailReceptor, ListaPathArchivos))
                            {
                                TempData["message"] = "Factura enviada a su email, por favor verifique su bandeja.";
                                TempData["typemessage"] = "1";
                            }
                            else
                            {
                                TempData["message"] = "Hubo un error al enviar la factura a su correo.";
                                TempData["typemessage"] = "2";
                            }

                            //borramos los archivos
                            if (System.IO.File.Exists(pathXML))
                            {
                                System.IO.File.Delete(pathXML);
                            }

FacturacionSAT.CSL.WEB/Areas/Admin/Views/AdminFactura/Add.cshtml
@model FacturacionSAT.CSL.WEB.Models.ViewModel.FacturacionViewModel
@{
    ViewBag.Title = "Nueva factura";
    SelectList ListaUsoCFDI = new SelectList(ViewBag.ListaUsoCFDI, "Id", "Value");

    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section css{
    <link href="~/Content/themes/smoothness/jquery.ui.all.css" rel="stylesheet" />

    <style>
        .form-control[disabled],
        .form-control[readonly] {
            color: #000 !important;
        }
        .validation-summary-valid {
            display: none;
        }

        .validation-summary-errors {
            color: #e80c4d;
            font-weight: bold;
            font-size: 1.1em;
        }
        .page-container .page-content {
            height: 100% !important;
        }
    </style>
}

@section featured
{

    @{
        var message = TempData["message"] ?? string.Empty;
        var typemessage = TempData["typemessage"] ?? string.Empty;
    }

    <div id="Error" class="progress-bar progress-bar-striped active errorCSL" style="display:none; width:100%">
        <h3></h3>
    </div>
    <div id="Success" class="progress-bar progress-bar-striped active successCSL" style="display:none; width:100%">
        <h3></h3>
    </div>

    <div class="col-md-12">
        <form action="@Url.Content("~/Admin/AdminFactura/Add")"  class="reimpresionForm" method="post" autocomplete="off">
            @{
                Html.EnableClientValidation(false);
                Html.EnableUnobtrusiveJavaScript(false);
            }
            @Html.ValidationSummary(false, "Se han generado los siguientes errores:")
            @Html.AntiForgeryToken()
            @Html.HiddenFor(d => d.Version)
            @Html.HiddenFor(d => d.TipoComprobante)
            @Html.HiddenFor(d => d.TipoComprobante_Generico)
            @Html.HiddenFor(d => d.Moneda_Generico)
            @Html.HiddenFor(d => d.Moneda)
            @Html.HiddenFor(d => d.Version)
            @Html.HiddenFor(d => d.Subtotal)
            @Html.HiddenFor(d => d.TotalDescuento)
            @Html.HiddenFor(d => d.Total)
            @Html.HiddenFor(d => d.LugarExpedicion)
            @Html.HiddenFor(d => d.CodigoBarraBoleto)
            @Html.HiddenFor(d => d.UsoCFDI_Generico)
            @Html.HiddenFor(d => d.FormaDePago)
            @Html.HiddenFor(d => d.RegimenFiscal)

            @for (int i = 0; i < Model.Conceptos.Count; i++)
            {
                @Html.HiddenFor(d => d.Conceptos[i].Cantidad)
                @Html.HiddenFor(d => d.Conceptos[i].ClaveProducto)
                @Html.HiddenFor(d => d.Conceptos[i].ClaveProducto_Generico)
                @Html.HiddenFor(d => d.Conceptos[i].ClaveUnidad)
                @Html.HiddenFor(d => d.Conceptos[i].ClaveUnidad_Generico)
                @Html.HiddenFor(d => d.Conceptos[i].CuentaPredial)
                @Html.HiddenFor(d => d.Conceptos[i].Descripcion)
                @Html.HiddenFor(d => d.Conceptos[i].Descuento)
                @Html.HiddenFor(d => d.Conceptos[i].PrecioUnitario)
                @Html.HiddenFor(d => d.Conceptos[i].Unidad)

                for (int x = 0; x < Model.Conceptos[i].Impuestos.Count; x++)
                {
                    @Html.HiddenFor(d => d.Conceptos[i].Impuestos[x].TipoFactor)
                    @Html.HiddenFor(d => d.Conceptos[i].Impuestos[x].Importe)
                    @Html.HiddenFor(d => d.Conceptos[i].Impuestos[x].Nombre)
                    @Html.HiddenFor(d => d.Conceptos[i].Impuestos[x].TasaOCuota)
                    @Html.HiddenFor(d => d.Conceptos[i].Impuestos[x].Clave_Impuesto)
                }
            }


            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(d => d.Folio)
                    @Html.TextBoxFor(d => d.Folio, "", new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessage("Folio", new { @class = "text-danger" })

                    @Html.LabelFor(d => d.TipoComprobante)
                    @Html.TextBoxFor(d => d.TipoComprobante_Generico, "", new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessage("TipoComprobante", new { @class = "text-danger" })

                    @Html.LabelFor(d => d.UsoCFDI)
                    @Html.DropDownListFor(d => d.UsoCFDI, ListaUsoCFDI, new { @class = "form-control" })
                    @Html.ValidationMessage("UsoCFDI", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(d => d.FormaDePago)
                    @Html.TextBoxFor(d => d.FormaDePago_Generico, "", new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessage("FormaDePago", new { @class = "text-danger" })

                    @Html.LabelFor(d => d.Fecha)
                    @Html.TextBoxFor(d => d.Fecha, "{0:yyyy/MM/dd HH:mm:ss}", new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessage("Fecha", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(d => d.Moneda)
                    @Html.TextBoxFor(d => d.Moneda_Generico, "", new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessage("Moneda", new { @class = "text-danger" })

                    @Html.LabelFor(d => d.RegimenFiscal)
                    @Html.TextBoxFor(d => d.RegimenFiscal_Generico, "", new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessage("RegimenFiscal", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <hr />
            <h5 class="tituloForm">Datos del cliente</h5>
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(d => d.RFCReceptor)
                    @Html.TextBoxFor(d => d.RFCReceptor, "", new { @class = "form-control", @readonly = "true" })
                    @Html.ValidationMessage("RFCReceptor", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(d => d.RazonSocial)
                    @if (string.IsNullOrEmpty(Model.RazonSocial))
                    {
                        @Html.TextBoxFor(d => d.RazonSocial, "", new { @class = "form-control" })
                    }
                    else
                    {
                        @Html.TextBoxFor(d => d.RazonSocial, "", new { @class = "form-control", @readonly = "true" })
                    }
                    @Html.ValidationMessage("RazonSocial", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(d => d.EmailReceptor)
                    @if (string.IsNullOrEmpty(Model.EmailReceptor))
                    {
                        @Html.TextBoxFor(d => d.EmailReceptor, "", new { @class = "form-control" })
                    }
                    else
                    {
                        @Html.TextBoxFor(d => d.EmailReceptor, "", new { @class = "form-control", @readonly = "true" })
                    }
                    @Html.ValidationMessage("EmailReceptor", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <hr />
            <h5 class="tituloForm">Productos / Servicios</h5>
            <div class="row">
                <table id="tblProdServ" class="table">
                    <thead>
                        <tr>
                            <th> Cantidad </th>
                            <th> Descripción </th>
                            <th> Producto / Servicio </th>
                            <th> Unidad de medida </th>
                            <th> Precio unitario </th>
                            <th> Descuento del boleto </th>
                            <th> Nombre del impuesto </th>
                            <th> Porcentaje del impuesto </th>
                            <th> Importe del impuesto </th>
                            <th> Total </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Conceptos)
                        {
                            <tr>
                                <td> @item.Cantidad  </td>
                                <td> @item.Descripcion </td>
                                <td> @item.ClaveProducto_Generico </td>
                                <td> @item.ClaveUnidad_Generico </td>
                                <td> @item.PrecioUnitario </td>
                                <td> @item.Descuento </td>
                                <td> @item.Impuestos[0].Nombre  </td>
                                <td> @item.Impuestos[0].TasaOCuota</td>
                                <td> @item.Impuestos[0].Importe  </td>
                                <td> @(item.PrecioUnitario + @item.Impuestos[0].Importe - item.Descuento)</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <br />
            <hr />
            <div style="text-align:right ">
                <a id="regresar" href="@Url.Action("Index", "AdminFactura")" class="btn btn-danger"><i class="icon-prev"></i>Regresar</a>
                <input type="submit" id="btnSubmit" class="btn btn-success" value="Generar factura" />
            </div>
        </form>
    </div>

    <script>
        var message = '@message';
        var typemessage = '@typemessage';
    </script>
}
@section script{
    <script type="text/javascript" src="@Url.Content("~/Content/js/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/mensajeDeError.js")"></script>
    <script>
        jQuery(document).ready(function () {
            Mensaje(message, typemessage);

            $('form').on('submit', function () {
                document.getElementById("btnSubmit").value = "Generando factura, por favor espere...";
                document.getElementById("btnSubmit").disabled = true;
            });

            var tblProdServ = $("#tblProdServ").DataTable({
                "language":
                {
                   "url": "@Url.Content("~/Content/assets/json/Spanish.json")"
                },
                "columnDefs": [
                   {
                       "targets": [0],
                       render: function (data, type, row) {
                           var value = row[0].replace(',', '.');
                           return value;
                       }
                   },
                   {
                       "targets": [4],
                       render: function (data, type, row) {
                           var value = '$ ' + row[4].replace(',', '.');
                           return value;
                       }
                    },
                    {
                        "targets": [5],
                        render: $.fn.dataTable.render.number(',', '.', 2, '$')
                    },
                   {
                       "targets": [6],
                       render: function (data, type, row) {
                           var value = row[6].replace(',', '.');
                           return value;
                       }
                   },
                   {
                       "targets": [7],
                       render: function (data, type, row) {
                           var value = '$ ' + row[7].replace(',', '.') ;
                            return value;
                       }
                   },
                   {
                       "targets": [8],
                       render: function (data, type, row) {
                           var value = '$ ' + row[8].replace(',', '.');
                           return value;
                       }

                    }
                    ,
                    {
                        "targets": [9],
                        render: $.fn.dataTable.render.number(',', '.', 2, '$')

                    }
               ]
            });

            $("#UsoCFDI").on("change", function () {
                var usoCFDI_Generico = $(this).find("option:selected").text();
                $("#UsoCFDI_Generico").val(usoCFDI_Generico);
            });
    });
    </script>
}