FacturacionSAT.CSL.WEB/Areas/Admin/Controllers/CFDIFormaPagoController.cs
using FacturacionSAT.CSL.WEB.Models;
using FacturacionSAT.CSL.WEB.App_Start;
using FacturacionSAT.CSL.WEB.Models.Datos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;

namespace FacturacionSAT.CSL.WEB.Areas.Admin.Controllers
{
    public class CFDIFormaPagoController : Controller
    {
        private TokenProcessor Token = TokenProcessor.GetInstance();
        string Conexion = ConfigurationManager.AppSettings.Get("strConnection");
        // GET: Admin/CFDIFormaPago
        public ActionResult Index()
        {
            try
            {
                CFDIFormaPago_AuryModels CFDIFormaPago = new CFDIFormaPago_AuryModels();
                CFDIFormaPagoDatos CFDIDatos = new CFDIFormaPagoDatos();
                AuxSQLModel oAuxSQLModel = new AuxSQLModel();
                oAuxSQLModel.Conexion = Conexion;
                CFDIFormaPago.ListaCFDIFP = CFDIDatos.ListaFP(oAuxSQLModel);
                return View(CFDIFormaPago);
            }
            catch (Exception)
            {
                CFDIFormaPagoDetalleModels CFDIFormaPago = new CFDIFormaPagoDetalleModels();
                TempData["typemessage"] = "2";
                TempData["message"] = "Ocurrió un error al guardar el registro.";
                return View(CFDIFormaPago);
            }
        }

        [HttpGet]
        public ActionResult UpdateCFDIFP(string id)
        {
            try
            {
                Token.SaveToken();
                CFDIFormaPago_AuryModels CFDIFormaPago = new CFDIFormaPago_AuryModels();
                CFDIFormaPagoDatos CFDIDatos = new CFDIFormaPagoDatos();
                CFDIFormaPago.Conexion = Conexion;
                CFDIFormaPago.ID_FormaPago = id;
                CFDIFormaPago.ListaCFDIDetalleCMB = CFDIDatos.ListaCFDI_CMB(CFDIFormaPago);
                CFDIFormaPago = CFDIDatos.GetCFDIFPDitail(CFDIFormaPago);
                return View(CFDIFormaPago);            
            }
            catch (Exception ex)            
            {
                throw ex;
            }
        }
        [HttpPost]
        public ActionResult UpdateCFDIFP(CFDIFormaPago_AuryModels item)
        {
            try
            {
                if (Token.IsTokenValid())
                {
                    CFDIFormaPagoDatos CFDIDatosFP = new CFDIFormaPagoDatos();
                    item.Conexion = Conexion;
                    if (ModelState.IsValid)
                    {
                        item.Id_usuario = User.Identity.Name;
                        item = CFDIDatosFP.UpdateCFDIFP(item);

                        if (item.Completado == true)
                        {
                            TempData["typemessage"] = "1";
                            TempData["message"] = "El registro se guardo correctamente.";
                            Token.ResetToken();
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            TempData["typemessage"] = "2";
                            TempData["message"] = "Ocurrió un error al guardar el registro.";
                            return View(item);
                        }
                    }
                    else
                    {
                        item.ListaCFDIDetalleCMB = CFDIDatosFP.ListaCFDI_CMB(item);
                        return View(item);
                    }
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

FacturacionSAT.CSL.WEB/Areas/Admin/Views/CFDIFormaPago/Index.cshtml
@model FacturacionSAT.CSL.WEB.Models.CFDIFormaPago_AuryModels
@{
                /**/

                ViewBag.Title = "Index";
                Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section featured{
    @{             
      var message = TempData["message"] ?? string.Empty;
      var typemessage = TempData["typemessage"] ?? string.Empty;
    }
    <div id="Error" class="progress-bar progress-bar-striped active errorCSL" style="display:none; width:100%">
        <h3></h3>
    </div>
    <div id="Success" class="progress-bar progress-bar-striped active successCSL" style="display:none; width:100%">
        <h3></h3>
    </div>
    <div class="page-title">
        <h2><span class="fa fa-arrow-circle-o-left"></span> CFDI FORMA DE PAGO</h2>
    </div>
    <!-- END PAGE TITLE -->
    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">
        <div class="row">
            <div class="col-md-12">
                <!-- START DEFAULT DATATABLE -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                        <ul class="panel-controls">
                            <li><a href="#" class="btn btn-default btnCrear disabled"><span class="fa fa-plus"></span> Nuevo</a></li>
                            <li><a href="#" class="panel-collapse exsa"><span class="fa fa-angle-down"></span></a></li>
                            <li><a href="#" class="panel-fullscreen exsa"><span class="fa fa-expand"></span></a></li>
                        </ul>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>Descripción</th>
                                        <th>Tipo de Pago</th>
                                        <th>Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.ListaCFDIFP)
                                    {
                                        <tr id="@item.ID_FormaPago">
                                            <td>@item.TipoPago</td>
                                            <td>@item.TipoDePago.Descripcion</td>                                            
                                            <td style="text-align:center;">
                                                <div class="visible-md visible-lg hidden-sm hidden-xs">
                                                    <a title="Editar" href="@Url.Action("UpdateCFDIFP", "CFDIFormaPago", new { id =item.ID_FormaPago})" class="btn btn-yellow tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>                                                  
                                                </div>
                                                <div class="visible-xs visible-sm hidden-md hidden-lg">
                                                    <div class="btn-group">
                                                        <a class="btn btn-danger dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
                                                            <i class="fa fa-cog"></i> <span class="caret"></span>
                                                        </a>
                                                        <ul role="menu" class="dropdown-menu pull-right dropdown-dark">
                                                            <li>
                                                                <a role="menuitem" tabindex="-1" href="@Url.Action("UpdateCFDIFP", "CFDIFormaPago", new { id = item.ID_FormaPago})">
                                                                    <i class="fa fa-edit"></i> Editar
                                                                </a>
                                                            </li>                                                           
                                                        </ul>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                     }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END DEFAULT DATATABLE -->
            </div>
        </div>
    </div>
    <!-- PAGE CONTENT WRAPPER -->
    <div class="message-box animated fadeIn" data-sound="alert" id="mb-remove-row">
        <div class="mb-container">
            <div class="mb-middle">               
                <div class="mb-footer">
                    <div class="pull-right">
                        <button class="btn btn-success btn-lg mb-control-yes">Si</button>
                        <button class="btn btn-default btn-lg mb-control-close">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    var message = '@message';
    var typemessage = '@typemessage';
    </script>
}
@section script
{
    @*<script type="text/javascript" src="@Url.Content("~/Content/js/demo_tables.js")"></script>*@
    <script type="text/javascript" src="@Url.Content("~/Content/js/demo_DatosEmisor.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/mensajeDeError.js")"></script>
    <script>
        jQuery(document).ready(function () {
            Mensaje(message, typemessage);
        });
    </script>
}

FacturacionSAT.CSL.WEB/Areas/Admin/Views/CFDIFormaPago/UpdateCFDIFP.cshtml
@model FacturacionSAT.CSL.WEB.Models.CFDIFormaPago_AuryModels
@{
    /**/

    ViewBag.Title = "UpdateCFDIFP";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section featured{

    @{
        var message = TempData["message"] ?? string.Empty;
        var typemessage = TempData["typemessage"] ?? string.Empty;
    }
    <div class="row">
        <div id="Error" class="progress-bar progress-bar-striped active errorCSL" style="display:none; width:100%">
            <h3></h3>
        </div>
        <div id="Success" class="progress-bar progress-bar-striped active successCSL" style="display:none; width:100%">
            <h3></h3>
        </div>
        <div class="col-md-12">
            @{Html.EnableClientValidation(false); }
            @using (Html.BeginForm("UpdateCFDIFP", "CFDIFormaPago", FormMethod.Post, new { id = "form-FormaPago", @class = "form-horizontal", autocomplete = "off" }))
            {

                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ID_FormaPago)
                @Html.ValidationSummary(false, "Hay errores en la captura de información:", new { @class = "text-danger" }) //Server
                <div id="validation_summary" class="field_error "></div> //JS

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Editar</strong> CFDIFormaPago</h3>
                        <ul class="panel-controls">
                            <li><a href="#" class="panel-remove exsa"><span class="fa fa-times"></span></a></li>
                        </ul>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-12">

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-12 col-xs-12 control-label text-center">Descripción de Pago</label>
                                    <div class="col-md-12 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                            @Html.TextBoxFor(model => model.TipoPago, new { id = "TipoPago", @class = "form-control", @readonly = "true" })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.TipoPago)
                                        <span class="help-block">Descripcion de Pago</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-12 col-xs-12 control-label text-center">Metodo de Pago</label>
                                    <div class="col-md-12 col-xs-12">
                                        @Html.DropDownListFor(model => model.TipoDePago.Id_cfdiFormaPagoDetalle, new SelectList(Model.ListaCFDIDetalleCMB, "Id_cfdiFormaPagoDetalle", "Descripcion"), new { id = "Id_cfdiFormaPagoDetalle", @class = "form-control ", data_live_search = "true" })
                                        @Html.ValidationMessageFor(model => model.TipoDePago.Id_cfdiFormaPagoDetalle)
                                        <span class="help-block">Metodo de Pago</span>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="panel-footer">
                        <input type="submit" value="Modificar" class="btn btn-primary pull-right">
                        <a href="@Url.Action("Index","CFDIFormaPago")" class="btn btn-danger"><i class="icon-prev"></i>Cancelar</a>
                    </div>
                </div>
            }
        </div>
    </div>

    <script>
        var message = '@message';
        var typemessage = '@typemessage';
    </script>
}
@section script
{
    <script type="text/javascript" src="@Url.Content("~/Content/js/plugins/bootstrap/bootstrap-select.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/mensajeDeError.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/plugins/jquery-validation/jquery.validate.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/validaciones/additionals.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/FormaPago.js")"></script>
    <script>
        jQuery(document).ready(function () {
            Mensaje(message, typemessage);
            FormaPago.init();
        });
    </script>
}